version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-vol:${WP_PATH}
    depends_on:
      - wordpress
    networks:
      - incep-net
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        - "WP_PATH=${WP_PATH}"
    volumes:
      - wp-vol:${WP_PATH}
    depends_on:
      - mariadb
    networks:
      - incep-net
    restart: on-failure
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - WP_PATH
      - WP_URL
      - WP_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL
      - WP_EDITOR_USER
      - WP_EDITOR_PASS
      - WP_EDITOR_EMAIL
  
  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - incep-net
    restart: on-failure
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_ROOT_PASS

volumes:
  wp-vol:
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/wp_vol"
      o: bind
  db-vol:
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/db_vol"
      o: bind

networks:
  incep-net: