version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:${WP_PATH}
    depends_on:
      - wordpress
    networks:
      - incep-net

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        - "WP_PATH=${WP_PATH}"
    ports:
      - "9000:9000"
    volumes:
      - wp-data:${WP_PATH}
    networks:
      - incep-net
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - WP_PATH
      - WP_URL
      - WP_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL

volumes:
  wp-data:

networks:
  incep-net: