version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/var/www/html

volumes:
  wp-data:
